# -*- coding: utf-8 -*-
"""LHR_Chapter1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qNk-F2e08RUuHdut9RfGcFs7NHDg_RFP

# 첫번째 문제

1. *두 수의 학을 구하는 코드를 작성하시오. 이 텍스트를 이탤릭체로 변경하시오.*
"""

약저1=3
약자2=5
print(약자1-약자2)
#(c)sh enter

약자1=3
약자2=5
print(약자1+약자2)
#(b)command m b

"""# 두 수의 뺄셈을 구하는 코드
(d)comm m a / comm m m
"""